version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "SneakersDb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qveze"
    ports:
      - "5432:5432"
    networks:
      - aboba
  blazorapp:
    image: ubik33/mega-server
    ports:
      - "8080:80"
      - "80:8080"
      - "5000:5000"
      - "5001:5001"
    networks:
      - aboba
networks:
  aboba:
    driver: bridge
